db:
  redis:
    emulate: ${EMULATE_REDIS:-true}
    host: ${HOST_REDIS:-localhost}
    port: ${PORT_REDIS:-6379}
    namespace: barbershop_gateway

# Plugin configuration
plugins:
  policies:
    package: './plugin-barbershop'